version: '3.8'
services:
  pocketbase:
    image:  ghcr.io/muchobien/pocketbase:0.35.0
    container_name: tolenaar-toto-backend
    restart: unless-stopped
    ports:
      - "8090:8080"
    volumes:
      - ./pb_data:/pb_data